IMAGE_NAME = "generic/rhel9"    # Base image of VM which is vagrant box of Centos8 18.04 TLS
BOX_VERSION = "4.0.2" 
HOST_NAME = "server1"
CPU = 2
MEMORY = 4048
HDD = 15
IP = "192.168.56.2"

Vagrant.configure("2") do |config|
  config.vagrant.plugins = ['vagrant-disksize','vagrant-hostmanager']
  config.vm.box = IMAGE_NAME
  config.vm.box_version = BOX_VERSION
  config.vm.host_name = HOST_NAME   #Static hostname of the vm
  config.vm.box_check_update = false
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "private_network", ip: IP
  # config.vm.network "public_network"  # It will create a bridge network,make this vm
  # discoverable to the network.
  config.vm.synced_folder ".", "/vagrant_data"
  config.vm.define HOST_NAME do |i|
    config.vm.provider "virtualbox" do |vm|
      vm.name = HOST_NAME  # VM Name displayed on Virtualbox console.
      vm.gui = false
      vm.memory = MEMORY
      vm.cpus = CPU
    end
    config.vm.provision "shell", inline: <<-SHELL
    hostnamectl
    SHELL
  end
end
